include: package:flutter_lints/core.yaml

linter:
  rules:
    - always_declare_return_types
    - avoid_print
    - prefer_single_quotes
    - sort_child_properties_last
    - use_key_in_widget_constructors

analyzer:
  exclude:
    - "**/*.g.dart"
    - "**/*.freezed.dart"
  errors:
    invalid_annotation_target: ignore
    deprecated_member_use: info
    unnecessary_non_null_assertion: warning
    invalid_null_aware_operator: warning
    unchecked_use_of_nullable_value: error