name: interquatier
description: InterQuatier sports events app

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^2.24.0
  firebase_auth: ^4.15.0
  cloud_firestore: ^4.13.3
  firebase_storage: ^11.5.3
  image_picker: ^1.0.4
  cached_network_image: ^3.3.0
  provider: ^6.1.1
  intl: ^0.18.1
  go_router: ^12.1.1
  flutter_riverpod: ^2.4.9
  freezed_annotation: ^2.4.1
  json_annotation: ^4.8.1
  timeago: ^3.6.0
  image_cropper: ^5.0.1
  flutter_image_compress: ^2.1.0
  photo_view: ^0.14.0
  carousel_slider: ^4.2.1
  firebase_messaging: ^14.7.4
  flutter_local_notifications: ^16.1.0
  firebase_dynamic_links: ^5.4.4
  url_launcher: ^6.2.1
  record: ^4.4.4
  path_provider: ^2.0.15
  ffmpeg_kit_flutter: ^5.1.0
  permission_handler: ^10.2.0
  just_audio: ^0.9.36

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  build_runner: ^2.4.7
  freezed: ^2.4.5
  json_serializable: ^6.7.1