server:
  port: 8080

spring:
  cache:
    type: caffeine
    caffeine:
      spec: maximumSize=500,expireAfterWrite=300s

logging:
  level:
    com.example.interquatier: DEBUG
    org.springframework.web: INFO 